### ISSUE TITLE
Issues with modern Meteor 1.11.x

### ISSUE THREAD

**Issue by mrSidX** [bioborg/eliberate#1]
Has anyone ran this on the latest Meteor 1.11?

Any luck?

I'm stuck on this trace:

`W20201118-10:24:42.102(-7)? (STDERR) /Users/sid/.meteor/packages/meteor-tool/.1.11.1.95af9c.g0b4t++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20201118-10:24:42.202(-7)? (STDERR) 						throw(ex);
W20201118-10:24:42.203(-7)? (STDERR) 						^
W20201118-10:24:42.203(-7)? (STDERR) 
W20201118-10:24:42.203(-7)? (STDERR) ReferenceError: FlowRouter is not defined
W20201118-10:24:42.203(-7)? (STDERR)     at module (Client/lib/router.js:1:1)
W20201118-10:24:42.204(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201118-10:24:42.204(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201118-10:24:42.204(-7)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20201118-10:24:42.204(-7)? (STDERR)     at /Users/sid/eliberate/.meteor/local/build/programs/server/app/app.js:4679:1
W20201118-10:24:42.205(-7)? (STDERR)     at /Users/sid/eliberate/.meteor/local/build/programs/server/boot.js:401:38
W20201118-10:24:42.205(-7)? (STDERR)     at Array.forEach (<anonymous>)
W20201118-10:24:42.205(-7)? (STDERR)     at /Users/sid/eliberate/.meteor/local/build/programs/server/boot.js:226:21
W20201118-10:24:42.205(-7)? (STDERR)     at /Users/sid/eliberate/.meteor/local/build/programs/server/boot.js:464:7
W20201118-10:24:42.234(-7)? (STDERR)     at Function.run (/Users/sid/eliberate/.meteor/local/build/programs/server/profile.js:280:14)
W20201118-10:24:42.234(-7)? (STDERR)     at /Users/sid/eliberate/.meteor/local/build/programs/server/boot.js:463:13
=> Exited with code: 1
`

I'm trying to iron out the packages and update them, but I'm stuck on this err

**Comment by bioborg** [comment]
Looks to me like flowrouter is missing?
https://github.com/kadirahq/flow-router (STDERR) ReferenceError: FlowRouter
is not defined

**Comment by mrSidX** [comment]
Anything I need to know about this app in order to build a Docker container?  
... on Ubuntu?

**Comment by mrSidX** [comment]
So I'm able to get it running in Meteor without dockerizing, though I'm trying to get it to it's proper functionality...

I get it to run and I'm able to connect by running `meteor` in the command to bind to port 3000, but I don't seem to get it running as in this demo video : https://www.youtube.com/watch?v=5qjKh_OeKjs&t=61s

When managing meetings and such, I tend to get these errors:
Perhaps I'm deploying / doing something wrong.


```
I20201120-16:21:43.860(0)? Exception while invoking method '/attendees/insert' TypeError: Cannot read property '_id' of undefined
I20201120-16:21:43.861(0)?     at insert (Server/permissions.js:132:54)
I20201120-16:21:43.861(0)?     at self._validators.insert.allow.every.validator (packages/allow-deny/allow-deny.js:246:13)
I20201120-16:21:43.861(0)?     at Array.every (<anonymous>)
I20201120-16:21:43.862(0)?     at CollectionPrototype._validatedInsert (packages/allow-deny/allow-deny.js:245:37)
I20201120-16:21:43.862(0)?     at MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
I20201120-16:21:43.862(0)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20201120-16:21:43.862(0)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20201120-16:21:43.863(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20201120-16:21:43.863(0)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20201120-16:21:43.863(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20201120-16:21:43.864(0)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20201120-16:21:43.864(0)?     at new Promise (<anonymous>)
I20201120-16:21:43.864(0)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20201120-16:21:43.865(0)?     at packages/ddp-server/livedata_server.js:559:43
I20201120-16:23:00.087(0)? Exception while invoking method '/attendees/insert' TypeError: Cannot read property '_id' of undefined
I20201120-16:23:00.087(0)?     at insert (Server/permissions.js:132:54)
I20201120-16:23:00.088(0)?     at self._validators.insert.allow.every.validator (packages/allow-deny/allow-deny.js:246:13)
I20201120-16:23:00.088(0)?     at Array.every (<anonymous>)
I20201120-16:23:00.089(0)?     at CollectionPrototype._validatedInsert (packages/allow-deny/allow-deny.js:245:37)
I20201120-16:23:00.089(0)?     at MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
I20201120-16:23:00.089(0)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20201120-16:23:00.089(0)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20201120-16:23:00.090(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20201120-16:23:00.090(0)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20201120-16:23:00.090(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20201120-16:23:00.090(0)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20201120-16:23:00.091(0)?     at new Promise (<anonymous>)
I20201120-16:23:00.091(0)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20201120-16:23:00.091(0)?     at packages/ddp-server/livedata_server.js:559:43
```

I appreciate you help
